#ifndef BRIGHTFX_H
#define BRIGHTFX_H

#pragma once

/* Generated by cbindgen from brightfx-ffi. Do not edit by hand; run core/scripts/gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle. Single-threaded: drive one handle from one thread.
 */
typedef struct BfxSimulation BfxSimulation;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a simulation seeded with `seed`, starting from the default config.
 * Never fails; load a real config with `bfx_set_config`.
 */
struct BfxSimulation *bfx_simulation_new(uint64_t seed);

/**
 * Frees a simulation. Safe to call with NULL. The handle must not be used
 * afterwards.
 *
 * # Safety
 * `sim` must be a pointer returned by `bfx_simulation_new`, freed at most once.
 */
void bfx_simulation_free(struct BfxSimulation *sim);

/**
 * Loads a JSON config. Returns an owned JSON envelope the caller must release
 * with `bfx_string_free`:
 * `{"ok":true,"clamped":[...],"warnings":[...]}` or `{"ok":false,"error":"..."}`.
 *
 * # Safety
 * `sim` must be a valid handle or NULL; `json` must be a NUL-terminated
 * string or NULL.
 */
char *bfx_set_config(struct BfxSimulation *sim, const char *json);

/**
 * Releases a string returned by `bfx_set_config` or `bfx_set_viewport`
 * (any function in this library that returns an owned `char*`). Safe to
 * call with NULL.
 *
 * # Safety
 * `text` must be a pointer returned by this library, freed at most once.
 */
void bfx_string_free(char *text);

/**
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
void bfx_set_emitter(struct BfxSimulation *sim, float x, float y, float vx, float vy, bool active);

/**
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
void bfx_trigger_burst(struct BfxSimulation *sim);

/**
 * Advances the simulation by `dt` seconds.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
void bfx_advance(struct BfxSimulation *sim, float dt);

/**
 * Runs baked playback on the config's emitter track through the 1/60 s
 * grid point at or after `time`, so every trigger authored at or before
 * `time` has fired and the simulation may sit up to one step past it: a
 * seek at or after the previous one steps forward
 * from it, and any other call sequence -- a backward seek, or any
 * `bfx_advance`, `bfx_trigger_burst`, `bfx_set_emitter`, or
 * `bfx_set_config` since -- replays from t=0, giving the same buffer
 * either way.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
void bfx_seek(struct BfxSimulation *sim, float time);

/**
 * Start of the particle buffer: `bfx_particle_count() * bfx_particle_floats()`
 * contiguous floats. Returns NULL for a NULL handle. Valid until the next
 * `bfx_advance`, `bfx_seek`, or `bfx_trigger_burst`.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
const float *bfx_buffer_ptr(const struct BfxSimulation *sim);

/**
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
uint32_t bfx_particle_count(const struct BfxSimulation *sim);

/**
 * Floats per particle in the buffer. Hosts derive their stride from this
 * rather than hardcoding it.
 */
uint32_t bfx_particle_floats(void);

/**
 * Whether a panic has poisoned this simulation. A poisoned simulation is
 * inert: every operation is a no-op, `bfx_particle_count` reports 0, and
 * `bfx_set_config` returns an error envelope. Recover by freeing the
 * handle and creating a new one. Returns `false` for a NULL handle.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
bool bfx_is_poisoned(const struct BfxSimulation *sim);

/**
 * Allocates the frame for a `width x height` device-pixel viewport at
 * `scale` device pixels per logical unit. Returns an owned envelope the
 * caller must release with `bfx_string_free`:
 * `{"ok":true,"clamped":[...],"warnings":[...]}` or `{"ok":false,"error":"..."}`.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
char *bfx_set_viewport(struct BfxSimulation *sim, uint32_t width, uint32_t height, float scale);

/**
 * Rasterizes the current particle buffer into the frame. A no-op until
 * `bfx_set_viewport` succeeds.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
void bfx_render(struct BfxSimulation *sim);

/**
 * Start of the frame: `bfx_frame_len()` bytes of premultiplied RGBA8,
 * row-major, `bfx_frame_width() * 4` bytes per row. Returns NULL for a
 * NULL handle. Valid until the next `bfx_render`; the address is stable
 * until the next `bfx_set_viewport`.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
const uint8_t *bfx_frame_ptr(const struct BfxSimulation *sim);

/**
 * Byte length of the frame; 0 before a viewport is set or when poisoned.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
uint32_t bfx_frame_len(const struct BfxSimulation *sim);

/**
 * Width of the frame in device pixels; 0 before a viewport is set or when
 * poisoned.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
uint32_t bfx_frame_width(const struct BfxSimulation *sim);

/**
 * Height of the frame in device pixels; 0 before a viewport is set or when
 * poisoned.
 *
 * # Safety
 * `sim` must be a valid handle or NULL.
 */
uint32_t bfx_frame_height(const struct BfxSimulation *sim);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BRIGHTFX_H */
